### ISSUE TITLE
Unable to boot TAILS

### ISSUE THREAD

**Issue by colindean** [vonbrownie/grubs#1]
I've got DBAN, Gparted Live, and Memtest working, but I'm seemingly unable to get TAILS 1.1.1 to work.

It says:

```
error: cannot read the Linux header.
error: you need to load the kernel first.
```

I tried modifying the `grub.conf` to use `vmlinuz2` and `initrd2.img` to mirror the `liveamd64.cfg` isolinux config found in the isolinux folder in the TAILS iso.

This is what I've got for TAILS in my `grub.cfg` at the moment:

```
menuentry "TAILS - The Amnesic Incognito Live System" {
    set iso="/iso/tails-i386-1.1.1.iso"
    loopback loop $iso
    linux (loop)/live/vmlinuz2 boot=live config live-media=removable  apparmor=1 security=apparmor nopersistent noprompt quiet timezone=America/New_York block.events_dfl_poll_msecs=1000 splash nox11autologin module=Tails findiso=$iso quiet_
    initrd (loop)/live/initrd2.img
}
```

I added the `apparmor=1 security=apparmor` based on TAILS configuration.

Here's what's in the `isolinux/live.cfg` on TAILS iso:

```
label live-amd64
    menu label Live amd64
    kernel /live/vmlinuz2
    append initrd=/live/initrd2.img boot=live config live-media=removable apparmor=1 security=apparmor nopersistent noprompt timezone=Etc/UTC block.events_dfl_poll_msecs=1000 splash noautologin module=Tails  quiet
```

**Comment by colindean** [comment]
Ubuntu Mini is working.

Trying Crunchbang.

**Comment by colindean** [comment]
Crunchbang is failing. It starts, but can't get out of the initrd. Not sure why.

**Comment by dwarmstrong** [comment]
It can be a bit tricky to get the `menuentry` correct. This post on the Arch Wiki might prove helpful:
https://wiki.archlinux.org/index.php/Multiboot_USB_drive#Boot_entries_for_other_distributions
